### ISSUE TITLE
let binding in match expression

### ISSUE THREAD

**Issue by gitoleg** [xguerin/ppx_bitstring#12]
I'm trying to swap bits in `bitstring` in next way:
```
let swap bs = match%bitstring bs with
| {| a : 1; b : 1 |} -> 
    let%bitstring bs' = {|b : 1; a : 1 |} in bs'
``` 
And I have an error `Uninterpreted extension 'bitstring'.` at last line. Could you tell please, what is going on? May be I'm doing something wrong ?

And there is one minor issue with semicolon at the end of pattern:
```
let test bs = match%bitstring bs with 
  | {| a : 1; b : 1 |} -> 42 
```
this one works fine, but
```
let test bs = match%bitstring bs with 
  | {| a : 1; b : 1; |} -> 42 
```
fails with error `Error: Format error: " "`

**Comment by xguerin** [comment]
It looks like it is chocking on the nesting. I'll look into it. As for the semicolon, it's a specificity of the original bitstring format. However, I definitely to work on error reporting.
