### ISSUE TITLE
Various syntactic issues

### ISSUE THREAD

**Issue by lebotlan** [xguerin/ppx_bitstring#41]
Hi,

I am playing with ppx_bitstring 1.3.3 and ocaml 4.04.0, but this is getting tough. It seems I have been cursed (most likely by a student, or a noisy child of mine).

Consider the file foo.ml (which github refuses to attach):

let my_bitstring =
  [%bitstring {|
   123: 16
  |}]

let%bitstring my_bitstring = {|
  ; 1 : 1
  ; 1 : 2
  ; 3 : 16 : bigendian |}

Which I compile with  ocamlfind ocamlc -c -package ppx_bitstring foo.ml
or with ocamlbuild -use-ocamlfind, using _tags:  package(ppx_bitstring).

A few problems arise:

 1 - If there is an extra ";" after the last field or before the first field, this gives : Error: Invalid number of fields in statement. (Minor problem)

 2 - If the field width is greater than 16, bitstring requires an int32. (Could be nicer. It is a 64-bit architecture anyway).

 3 -  let%bitstring is unrecognized : Error: Uninterpreted extension 'bitstring'.
      (On the line with let%bitstring)
      Because of this one, I have been thinking for a moment that ppx_bitstream was incorrectly installed.

      Actually, it works with a inner  let%bitstring ... in ...  but not with top-level lets.

Anyway, it is nice to keep the same look-and-feel than the original camlp4-bitstring library.

Cheers.

**Comment by xguerin** [comment]
I believe these issues are the consequence of me trying to stick to the original behavior:

1. This is explicitly enforced in the structure parser. I need to check how the `camlp4` handled this situation (I'm not quite sure anymore).

2. AFAICT this is also the case in the `camlp4` extension.

3. That is indeed a limitation. Top-level `let` bindings are not supported. If that's a feature you'd like to see implemented, may I suggest that you open a separate feature request for it ?

**Comment by lebotlan** [comment]
Thank you for your quick answer. A few last comments:

 1.  The examples in README.md  all have a leading ; in the fields. 

 2 . Sure? I have some vintage code that mentions yyy : 24   where yyy is an int.

 3.  I'll be glad to open a request :)

**Comment by xguerin** [comment]
1. That's most likely an oversight. I'll double check.
2. That should be supported. I'll check that as well.

**Comment by xguerin** [comment]
1/ is fixed. 2/ I created a new ticket. Closing.
