### ISSUE TITLE
Add support for OCaml 4.04.x

### ISSUE THREAD

**Issue by dakk** [xguerin/ppx_bitstring#44]
Hi, I just noticed that camlp4 is deprecated, so I'm switching from bitstring.syntax to ppx_bitstring; I'm trying to install ppx_bistring with ocaml 4.04, but opam return me this error:

```
dakk ~ opam install ppx_bitstring
The following dependencies couldn't be met:
  - ppx_bitstring -> ppx_driver < v0.9.0
Your request can't be satisfied:
  - ppx_driver<v0.9.0 is not available because your system doesn't comply with ocaml-version = "4.02.3".

No solution found, exiting
```
In your opam file I can't see a constraint for ppx_driver version; am I missing something?

**Comment by xguerin** [comment]
Yes, the AST has changed and as a result `ppx_driver` and `ppx_core` have changed. I just started to work on it.

**Comment by dakk** [comment]
Ok that's great

**Comment by xguerin** [comment]
Done, see d314d7a.

**Comment by dakk** [comment]
well done, thank you
