### ISSUE TITLE
Wrong extraction function?

### ISSUE THREAD

**Issue by briancaine** [xguerin/ppx_bitstring#46]
Hi,

So I've got this match in my code:
```
let mb = ("\000\000\145", 0, 24) in
match%bitstring mb with
| {| matched_value : 24 : bigendian |} -> matched_value
```
I'm expecting matched_value to equal 145. That is, three bytes, 0x0, 0x0, and 0x91 in bigendian order. But I'm getting `37120l` instead. (That seems to be `145 lsl 8`.)

I think the match syntax is using `Bitstring.extract_fastpath_int32_be_unsigned` and not shifting the result to the right to compensate for the 8 extra bits.

Am I correct or did I confuse something?

Thanks!

**Comment by xguerin** [comment]
Thanks for reporting this. I'm AFK for the moment but will check once I get back.
