### ISSUE TITLE
Failure to use ppx_bitstring with jbuilder

### ISSUE THREAD

**Issue by wtetzner** [xguerin/ppx_bitstring#49]
Hello, I've created a small project using jbuilder and ppx_bitstring. I keep getting the following error:

    Error: Uninterpreted extension 'bitstring'.

I'm also using Opam 2.0, so maybe that's causing an issue? I'm not sure.

Anyway, my project looks like this:

    % ls
    jbuild   wombat.ml  wombat.opam

jbuild:

    (jbuild_version 1)
    
    (executable
     ((name wombat)
      (libraries (core bitstring))
      (preprocess (pps (ppx_bitstring)))))
    
    (install
     ((section bin)
      (files ((wombat.exe as wombat)))))

wombat.opam:

    opam-version: "2.0"
    name: "wombat"
    maintainer: "Walter Tetzner"
    version: "0.1.0"
    build: [
      ["jbuilder" "build" "-p" name "-j" jobs]
    ]
    depends: [
      "bitstring"
      "ppx_bitstring" {build}
      "core"
      "jbuilder" {build}
      "ocaml-migrate-parsetree" {build}
    ]

wombat.ml:

    let () = let%bitstring fred = {| 0b10000001 : 8; 10 : 8 |} in
             fred

This is my jbuilder log:

    %  jbuilder build --verbose -p wombat -j 3
    # Workspace root: /mnt/c/Users/wtetzner/test-proj
    Running[0]: /mnt/c/Users/wtetzner/test-proj/_opam/bin/ocamlfind printconf path > /tmp/jbuildc8014c.output
    Running[1]: /mnt/c/Users/wtetzner/test-proj/_opam/bin/ocamlc.opt -config > /tmp/jbuild149eaa.output
    # Jbuilder context:
    #  ((name default)
    #   (kind default)
    #   (merlin true)
    #   (for_host ())
    #   (build_dir _build/default)
    #   (toplevel_path ())
    #   (ocaml_bin /mnt/c/Users/wtetzner/test-proj/_opam/bin)
    #   (ocaml /mnt/c/Users/wtetzner/test-proj/_opam/bin/ocaml)
    #   (ocamlc /mnt/c/Users/wtetzner/test-proj/_opam/bin/ocamlc.opt)
    #   (ocamlopt (/mnt/c/Users/wtetzner/test-proj/_opam/bin/ocamlopt.opt))
    #   (ocamldep /mnt/c/Users/wtetzner/test-proj/_opam/bin/ocamldep.opt)
    #   (ocamlmklib /mnt/c/Users/wtetzner/test-proj/_opam/bin/ocamlmklib.opt)
    #   (env ((OCAMLPARAM color=always,_)))
    #   (findlib_path (/mnt/c/Users/wtetzner/test-proj/_opam/lib))
    #   (arch_sixtyfour true)
    #   (natdynlink_supported true)
    #   (opam_vars ())
    #   (ocamlc_config
    #    ((architecture amd64)
    #     (asm as)
    #     (asm_cfi_supported true)
    #     (ast_impl_magic_number Caml1999M020)
    #     (ast_intf_magic_number Caml1999N018)
    #     (bytecomp_c_compiler
    #      "gcc -std=gnu99 -O2 -fno-strict-aliasing -fwrapv -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC")
    #     (bytecomp_c_libraries "-lm  -ldl -lcurses -lpthread                  ")
    #     (cc_profile -pg)
    #     (ccomp_type cc)
    #     (cma_magic_number Caml1999A012)
    #     (cmi_magic_number Caml1999I021)
    #     (cmo_magic_number Caml1999O011)
    #     (cmt_magic_number Caml2012T008)
    #     (cmx_magic_number Caml1999Y015)
    #     (cmxa_magic_number Caml1999Z014)
    #     (cmxs_magic_number Caml2007D002)
    #     (default_executable_name a.out)
    #     (exec_magic_number Caml1999X011)
    #     (ext_asm .s)
    #     (ext_dll .so)
    #     (ext_lib .a)
    #     (ext_obj .o)
    #     (flambda false)
    #     (host x86_64-unknown-linux-gnu)
    #     (model default)
    #     (native_c_compiler
    #      "gcc -std=gnu99 -O2 -fno-strict-aliasing -fwrapv -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT")
    #     (native_c_libraries "-lm  -ldl")
    #     (native_pack_linker "ld -r  -o ")
    #     (os_type Unix)
    #     (ranlib ranlib)
    #     (safe_string false)
    #     (spacetime false)
    #     (standard_library /mnt/c/Users/wtetzner/test-proj/_opam/lib/ocaml)
    #     (standard_library_default /mnt/c/Users/wtetzner/test-proj/_opam/lib/ocaml)
    #     (standard_runtime /mnt/c/Users/wtetzner/test-proj/_opam/bin/ocamlrun)
    #     (system linux)
    #     (systhread_supported true)
    #     (target x86_64-unknown-linux-gnu)
    #     (version 4.04.1)
    #     (with_frame_pointers false)))
    #   (which
    #    ((ocamlc (/mnt/c/Users/wtetzner/test-proj/_opam/bin/ocamlc.opt))
    #     (ocamlfind (/mnt/c/Users/wtetzner/test-proj/_opam/bin/ocamlfind)))))
    # Actual targets:
    # - alias install
    Running[2]: (cd _build/default && /mnt/c/Users/wtetzner/test-proj/_opam/bin/ocamlopt.opt -o .ppx/ppx_bitstring/ppx.exe -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ocaml-migrate-parsetree -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ocaml-migrate-parsetree/driver-main -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ocaml/compiler-libs -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ppx_bitstring -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/result /mnt/c/Users/wtetzner/test-proj/_opam/lib/ocaml/compiler-libs/ocamlcommon.cmxa /mnt/c/Users/wtetzner/test-proj/_opam/lib/result/result.cmxa /mnt/c/Users/wtetzner/test-proj/_opam/lib/ocaml-migrate-parsetree/migrate_parsetree.cmxa /mnt/c/Users/wtetzner/test-proj/_opam/lib/ocaml-migrate-parsetree/driver-main/migrate_parsetree_driver_main.cmxa)
    Running[3]: (cd _build/default && ./.ppx/ppx_bitstring/ppx.exe --dump-ast -o wombat.pp.ml --impl wombat.ml)
    Running[4]: (cd _build/default && /mnt/c/Users/wtetzner/test-proj/_opam/bin/ocamldep.opt -modules wombat.pp.ml) > _build/default/wombat.depends.ocamldep-output
    Running[5]: (cd _build/default && /mnt/c/Users/wtetzner/test-proj/_opam/bin/ocamlc.opt -w -40 -g -bin-annot -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/bin_prot -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/bitstring -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/core -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/core_kernel -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/fieldslib -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/num -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ocaml -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ocaml/threads -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ppx_assert -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ppx_bench -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ppx_expect -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ppx_inline_test -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/result -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/sexplib -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/typerep -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/variantslib -no-alias-deps -I . -o wombat.cmo -c -impl wombat.pp.ml)
    
    Command [5] exited with code 2:
    $ (cd _build/default && /mnt/c/Users/wtetzner/test-proj/_opam/bin/ocamlc.opt -w -40 -g -bin-annot -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/bin_prot -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/bitstring -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/core -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/core_kernel -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/fieldslib -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/num -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ocaml -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ocaml/threads -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ppx_assert -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ppx_bench -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ppx_expect -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/ppx_inline_test -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/result -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/sexplib -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/typerep -I /mnt/c/Users/wtetzner/test-proj/_opam/lib/variantslib -no-alias-deps -I . -o wombat.cmo -c -impl wombat.pp.ml)
    File "wombat.ml", line 2, characters 13-22:
    Error: Uninterpreted extension 'bitstring'.
    [1]

So it looks like `ppx_bitstring` _is_ being run, but isn't processing the extensions. Or am I misreading it?

**Comment by xguerin** [comment]
Hmm, that's a strange error that I don't seem to be able to reproduce (I had to change `wombat.ml` to make compile):

```ocaml
let () = let%bitstring fred = {| 0b10000001 : 8; 10 : 8 |} in
         ()
```

```
# Workspace root: /Users/xguerin/Sandbox/ppx_bitstring_49
Running[0]: /Users/xguerin/.opam/system/bin/ocamlfind printconf path > /var/folders/75/x8_96gdj6bj_l3rr509t_v_m0000gp/T/jbuildeb9e56.output
Running[1]: /usr/local/bin/ocamlc.opt -config > /var/folders/75/x8_96gdj6bj_l3rr509t_v_m0000gp/T/jbuild5123d8.output
# Jbuilder context:
#  ((name default)
#   (kind default)
#   (merlin true)
#   (for_host ())
#   (build_dir _build/default)
#   (toplevel_path (/Users/xguerin/.opam/system/lib/toplevel))
#   (ocaml_bin /usr/local/bin)
#   (ocaml /usr/local/bin/ocaml)
#   (ocamlc /usr/local/bin/ocamlc.opt)
#   (ocamlopt (/usr/local/bin/ocamlopt.opt))
#   (ocamldep /usr/local/bin/ocamldep.opt)
#   (ocamlmklib /usr/local/bin/ocamlmklib.opt)
#   (env ())
#   (findlib_path (/Users/xguerin/.opam/system/lib))
#   (arch_sixtyfour true)
#   (natdynlink_supported true)
#   (opam_vars ())
#   (ocamlc_config
#    ((architecture amd64)
#     (asm "clang -arch x86_64 -c")
#     (asm_cfi_supported true)
#     (ast_impl_magic_number Caml1999M020)
#     (ast_intf_magic_number Caml1999N018)
#     (bytecomp_c_compiler
#      "gcc  -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT ")
#     (bytecomp_c_libraries "-lcurses -lpthread                  ")
#     (cc_profile -pg)
#     (ccomp_type cc)
#     (cma_magic_number Caml1999A012)
#     (cmi_magic_number Caml1999I021)
#     (cmo_magic_number Caml1999O011)
#     (cmt_magic_number Caml2012T009)
#     (cmx_magic_number Caml1999Y015)
#     (cmxa_magic_number Caml1999Z014)
#     (cmxs_magic_number Caml2007D002)
#     (default_executable_name a.out)
#     (exec_magic_number Caml1999X011)
#     (ext_asm .s)
#     (ext_dll .so)
#     (ext_exe "")
#     (ext_lib .a)
#     (ext_obj .o)
#     (flambda false)
#     (host x86_64-apple-darwin17.0.0)
#     (int_size 63)
#     (model default)
#     (native_c_compiler
#      "gcc  -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT")
#     (native_c_libraries "")
#     (native_pack_linker "ld -r -arch x86_64  -o ")
#     (os_type Unix)
#     (profiling true)
#     (ranlib ranlib)
#     (safe_string false)
#     (spacetime false)
#     (standard_library /usr/local/lib/ocaml)
#     (standard_library_default /usr/local/lib/ocaml)
#     (standard_runtime /usr/local/bin/ocamlrun)
#     (system macosx)
#     (systhread_supported true)
#     (target x86_64-apple-darwin17.0.0)
#     (version 4.05.0)
#     (with_frame_pointers false)
#     (word_size 64)))
#   (which
#    ((ocamlc (/usr/local/bin/ocamlc.opt))
#     (ocamlfind (/Users/xguerin/.opam/system/bin/ocamlfind)))))
# Actual targets:
# - alias install
Running[2]: (cd _build/default && /usr/local/bin/ocamlopt.opt -o .ppx/ppx_bitstring/ppx.exe -I /Users/xguerin/.opam/system/lib/ocaml-migrate-parsetree -I /Users/xguerin/.opam/system/lib/ocaml-migrate-parsetree/driver-main -I /Users/xguerin/.opam/system/lib/ppx_bitstring -I /Users/xguerin/.opam/system/lib/ppx_tools_versioned -I /Users/xguerin/.opam/system/lib/result -I /usr/local/lib/ocaml -I /usr/local/lib/ocaml/compiler-libs /usr/local/lib/ocaml/compiler-libs/ocamlcommon.cmxa /Users/xguerin/.opam/system/lib/result/result.cmxa /Users/xguerin/.opam/system/lib/ocaml-migrate-parsetree/migrate_parsetree.cmxa /Users/xguerin/.opam/system/lib/ppx_tools_versioned/ppx_tools_versioned.cmxa /usr/local/lib/ocaml/str.cmxa /Users/xguerin/.opam/system/lib/ppx_bitstring/ppx_bitstring.cmxa /Users/xguerin/.opam/system/lib/ocaml-migrate-parsetree/driver-main/migrate_parsetree_driver_main.cmxa)
Running[3]: (cd _build/default && ./.ppx/ppx_bitstring/ppx.exe --dump-ast -o wombat.pp.ml --impl wombat.ml)
Running[4]: (cd _build/default && /usr/local/bin/ocamldep.opt -modules wombat.pp.ml) > _build/default/wombat.depends.ocamldep-output
Running[5]: (cd _build/default && /usr/local/bin/ocamlc.opt -w -40 -g -bin-annot -I /Users/xguerin/.opam/system/lib/base -I /Users/xguerin/.opam/system/lib/base/caml -I /Users/xguerin/.opam/system/lib/base/shadow_stdlib -I /Users/xguerin/.opam/system/lib/bin_prot -I /Users/xguerin/.opam/system/lib/bin_prot/shape -I /Users/xguerin/.opam/system/lib/bitstring -I /Users/xguerin/.opam/system/lib/core -I /Users/xguerin/.opam/system/lib/core_kernel -I /Users/xguerin/.opam/system/lib/core_kernel/base_for_tests -I /Users/xguerin/.opam/system/lib/fieldslib -I /Users/xguerin/.opam/system/lib/jane-street-headers -I /Users/xguerin/.opam/system/lib/num -I /Users/xguerin/.opam/system/lib/ppx_assert/runtime-lib -I /Users/xguerin/.opam/system/lib/ppx_bench/runtime-lib -I /Users/xguerin/.opam/system/lib/ppx_compare/runtime-lib -I /Users/xguerin/.opam/system/lib/ppx_deriving -I /Users/xguerin/.opam/system/lib/ppx_expect/collector -I /Users/xguerin/.opam/system/lib/ppx_expect/common -I /Users/xguerin/.opam/system/lib/ppx_expect/config -I /Users/xguerin/.opam/system/lib/ppx_hash/runtime-lib -I /Users/xguerin/.opam/system/lib/ppx_inline_test/config -I /Users/xguerin/.opam/system/lib/ppx_inline_test/runtime-lib -I /Users/xguerin/.opam/system/lib/result -I /Users/xguerin/.opam/system/lib/sexplib -I /Users/xguerin/.opam/system/lib/sexplib/0 -I /Users/xguerin/.opam/system/lib/sexplib/unix -I /Users/xguerin/.opam/system/lib/spawn -I /Users/xguerin/.opam/system/lib/stdio -I /Users/xguerin/.opam/system/lib/typerep -I /Users/xguerin/.opam/system/lib/variantslib -I /usr/local/lib/ocaml -I /usr/local/lib/ocaml/threads -no-alias-deps -I . -o wombat.cmo -c -impl wombat.pp.ml)
Output[5]:
File "wombat.ml", line 1, characters 9-73:
Warning 26: unused variable fred.
Running[6]: (cd _build/default && /usr/local/bin/ocamlopt.opt -w -40 -g -I /Users/xguerin/.opam/system/lib/base -I /Users/xguerin/.opam/system/lib/base/caml -I /Users/xguerin/.opam/system/lib/base/shadow_stdlib -I /Users/xguerin/.opam/system/lib/bin_prot -I /Users/xguerin/.opam/system/lib/bin_prot/shape -I /Users/xguerin/.opam/system/lib/bitstring -I /Users/xguerin/.opam/system/lib/core -I /Users/xguerin/.opam/system/lib/core_kernel -I /Users/xguerin/.opam/system/lib/core_kernel/base_for_tests -I /Users/xguerin/.opam/system/lib/fieldslib -I /Users/xguerin/.opam/system/lib/jane-street-headers -I /Users/xguerin/.opam/system/lib/num -I /Users/xguerin/.opam/system/lib/ppx_assert/runtime-lib -I /Users/xguerin/.opam/system/lib/ppx_bench/runtime-lib -I /Users/xguerin/.opam/system/lib/ppx_compare/runtime-lib -I /Users/xguerin/.opam/system/lib/ppx_deriving -I /Users/xguerin/.opam/system/lib/ppx_expect/collector -I /Users/xguerin/.opam/system/lib/ppx_expect/common -I /Users/xguerin/.opam/system/lib/ppx_expect/config -I /Users/xguerin/.opam/system/lib/ppx_hash/runtime-lib -I /Users/xguerin/.opam/system/lib/ppx_inline_test/config -I /Users/xguerin/.opam/system/lib/ppx_inline_test/runtime-lib -I /Users/xguerin/.opam/system/lib/result -I /Users/xguerin/.opam/system/lib/sexplib -I /Users/xguerin/.opam/system/lib/sexplib/0 -I /Users/xguerin/.opam/system/lib/sexplib/unix -I /Users/xguerin/.opam/system/lib/spawn -I /Users/xguerin/.opam/system/lib/stdio -I /Users/xguerin/.opam/system/lib/typerep -I /Users/xguerin/.opam/system/lib/variantslib -I /usr/local/lib/ocaml -I /usr/local/lib/ocaml/threads -intf-suffix .ml -no-alias-deps -I . -o wombat.cmx -c -impl wombat.pp.ml)
Output[6]:
File "wombat.ml", line 1, characters 9-73:
Warning 26: unused variable fred.
Running[7]: (cd _build/default && /usr/local/bin/ocamlopt.opt -w -40 -g -o wombat.exe -I /Users/xguerin/.opam/system/lib/base -I /Users/xguerin/.opam/system/lib/base/caml -I /Users/xguerin/.opam/system/lib/base/shadow_stdlib -I /Users/xguerin/.opam/system/lib/bin_prot -I /Users/xguerin/.opam/system/lib/bin_prot/shape -I /Users/xguerin/.opam/system/lib/bitstring -I /Users/xguerin/.opam/system/lib/core -I /Users/xguerin/.opam/system/lib/core_kernel -I /Users/xguerin/.opam/system/lib/core_kernel/base_for_tests -I /Users/xguerin/.opam/system/lib/fieldslib -I /Users/xguerin/.opam/system/lib/jane-street-headers -I /Users/xguerin/.opam/system/lib/num -I /Users/xguerin/.opam/system/lib/ppx_assert/runtime-lib -I /Users/xguerin/.opam/system/lib/ppx_bench/runtime-lib -I /Users/xguerin/.opam/system/lib/ppx_compare/runtime-lib -I /Users/xguerin/.opam/system/lib/ppx_deriving -I /Users/xguerin/.opam/system/lib/ppx_expect/collector -I /Users/xguerin/.opam/system/lib/ppx_expect/common -I /Users/xguerin/.opam/system/lib/ppx_expect/config -I /Users/xguerin/.opam/system/lib/ppx_hash/runtime-lib -I /Users/xguerin/.opam/system/lib/ppx_inline_test/config -I /Users/xguerin/.opam/system/lib/ppx_inline_test/runtime-lib -I /Users/xguerin/.opam/system/lib/result -I /Users/xguerin/.opam/system/lib/sexplib -I /Users/xguerin/.opam/system/lib/sexplib/0 -I /Users/xguerin/.opam/system/lib/sexplib/unix -I /Users/xguerin/.opam/system/lib/spawn -I /Users/xguerin/.opam/system/lib/stdio -I /Users/xguerin/.opam/system/lib/typerep -I /Users/xguerin/.opam/system/lib/variantslib -I /usr/local/lib/ocaml -I /usr/local/lib/ocaml/threads /Users/xguerin/.opam/system/lib/base/caml/caml.cmxa /Users/xguerin/.opam/system/lib/base/shadow_stdlib/shadow_stdlib.cmxa /Users/xguerin/.opam/system/lib/sexplib/0/sexplib0.cmxa /usr/local/lib/ocaml/unix.cmxa /Users/xguerin/.opam/system/lib/base/base.cmxa /Users/xguerin/.opam/system/lib/result/result.cmxa /usr/local/lib/ocaml/bigarray.cmxa /Users/xguerin/.opam/system/lib/fieldslib/fieldslib.cmxa /Users/xguerin/.opam/system/lib/ppx_compare/runtime-lib/ppx_compare_lib.cmxa /Users/xguerin/.opam/system/lib/ppx_deriving/ppx_deriving_runtime.cmxa /Users/xguerin/.opam/system/lib/sexplib/sexplib.cmxa /Users/xguerin/.opam/system/lib/variantslib/variantslib.cmxa /Users/xguerin/.opam/system/lib/bin_prot/shape/bin_shape_lib.cmxa /Users/xguerin/.opam/system/lib/ppx_inline_test/config/inline_test_config.cmxa /Users/xguerin/.opam/system/lib/ppx_hash/runtime-lib/ppx_hash_lib.cmxa /Users/xguerin/.opam/system/lib/ppx_inline_test/runtime-lib/ppx_inline_test_lib.cmxa /usr/local/lib/ocaml/nums.cmxa /Users/xguerin/.opam/system/lib/ppx_expect/common/expect_test_common.cmxa /Users/xguerin/.opam/system/lib/ppx_expect/config/expect_test_config.cmxa /Users/xguerin/.opam/system/lib/bin_prot/bin_prot.cmxa /Users/xguerin/.opam/system/lib/core_kernel/base_for_tests/base_for_tests.cmxa /Users/xguerin/.opam/system/lib/jane-street-headers/jane_street_headers.cmxa /Users/xguerin/.opam/system/lib/ppx_assert/runtime-lib/ppx_assert_lib.cmxa /Users/xguerin/.opam/system/lib/ppx_bench/runtime-lib/ppx_bench_lib.cmxa /Users/xguerin/.opam/system/lib/ppx_expect/collector/expect_test_collector.cmxa /Users/xguerin/.opam/system/lib/stdio/stdio.cmxa /Users/xguerin/.opam/system/lib/typerep/typerep_lib.cmxa /usr/local/lib/ocaml/threads/threads.cmxa /Users/xguerin/.opam/system/lib/core_kernel/core_kernel.cmxa /Users/xguerin/.opam/system/lib/sexplib/unix/sexplib_unix.cmxa /Users/xguerin/.opam/system/lib/spawn/spawn.cmxa /Users/xguerin/.opam/system/lib/core/core.cmxa /Users/xguerin/.opam/system/lib/bitstring/bitstring.cmxa wombat.cmx)
```

**Comment by wtetzner** [comment]
Thanks for looking at this.

After upgrading to 4.05.0 it started working.

**Comment by wtetzner** [comment]
For reference, I was using 4.04.1 when it was failing. I'm not sure if that was the cause, or if there was something wrong with my Opam state, and rebuilding it is what fixed the problem.

**Comment by xguerin** [comment]
Thanks for letting me know. I’ll try again with 4.04.1.

**Comment by xguerin** [comment]
Just tried with 4.04.1 and `ppx_bistring` 2.0.2 and could not reproduce the problem. I believe your version of `ppx_bitstring` was pre-OMP, which was not compatible with `jbuilder`.
