### ISSUE TITLE
Replace { pexp_desc } pattern matching with ppx_core

### ISSUE THREAD

**Issue by xguerin** [xguerin/ppx_bitstring#8]

**Comment by xguerin** [comment]
Explore https://github.com/janestreet/ppx_core for that job

**Comment by profmaad** [comment]
FYI, I have a branch that uses ppx_driver, and thus already depends on ppx_core.
https://github.com/profmaad/ppx_bitstring/tree/use-ppx-driver

**Comment by xguerin** [comment]
Thanks, I'll check it out.
