### ISSUE TITLE
release to opam

### ISSUE THREAD

**Issue by ivg** [xguerin/ppx_bitstring#9]
How far the project is from being released to `opam-repository`?

**Comment by xguerin** [comment]
I have not considered it, but it's functionally complete.

**Comment by ivg** [comment]
Cool, will you consider now, or want your version to be merged by the upstream?

The reason, why I'm asking, is that I want  to get rid of camlp4 in the [bap][1] package, and it is the only dependency that still needs `camlp4`.

[1]: https://github.com/BinaryAnalysisPlatform/bap

**Comment by xguerin** [comment]
Definitely. I'll look into it.

**Comment by xguerin** [comment]
I sent a pull request to opam-repos. I will close that ticket once the package is merged.

**Comment by ivg** [comment]
Great news, thanks a lot!

**Comment by xguerin** [comment]
Done.
